# 7-Numpy_Pandas

##Exercise 1: (Score : 1)
#Create a numpy array containing the numbers from 1 to 10, and then reshape it to a 2x5 matrix.



In [15]:
import numpy as np

In [12]:
array=np.arange(1,11)
print(array)
#reshape the array
matrix=array.reshape(2,5)
print (matrix)

[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [ ]:
-----------------------------------------------------------------------------------------------------------------------

##Exercise 2: (Score : 1)#
#Create a numpy array containing the numbers from 1 to 20, and then extract the elements between the 5th and 15th index.


In [25]:
array2=np.arange(1,21)
print(array2)
sliced_element=(array2[5:16])
print(sliced_element)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 6  7  8  9 10 11 12 13 14 15 16]


In [ ]:
----------------------------------------------------------------------------------------------------------------

##Exercise 3: (Score : 2)
#Create a Pandas series with the following data: {'apples': 3, 'bananas': 2, 'oranges': 1}. Then, add a new item to the series with the key 'pears' and the value 4.


In [5]:
import pandas as pd

In [9]:
data={'apples':3,'bananas':2,'oranges':1}
series=pd.Series(data)
#add a item to the series
series['pears']=4
print(series)

apples     3
bananas    2
oranges    1
pears      4
dtype: int64


In [ ]:
--------------------------------------------------------------------------------------------------

##Exercise 4: (Score : 2)
#Create a dataframe with the following columns: name, age, and gender. The dataframe should have 10 rows of data.


In [18]:
#create a dictionary with the data 
data={'Name': ['Allu Arjun','Bavana','Divya unni','Gayathri','Mammuty','Mohanlal','Dileep','Kavya madavan','Jayaram','Dulqar'],
      'Age':[40,30,46,30,65,64,57,37,54,40],
       'Gender':['Male','Female','Female','Female','Male','Male','Male','Female','Male','Male']}

 #crete the data frame
df=pd.DataFrame(data)
print(df)

            Name  Age  Gender
0     Allu Arjun   40    Male
1         Bavana   30  Female
2     Divya unni   46  Female
3       Gayathri   30  Female
4        Mammuty   65    Male
5       Mohanlal   64    Male
6         Dileep   57    Male
7  Kavya madavan   37  Female
8        Jayaram   54    Male
9         Dulqar   40    Male


In [ ]:
-----------------------------------------------------------------------------------------------------------------


##Exercise 5: (Score : 1)
#Add a new column to the data frame created in question 1, called occupation. The values for this column should be Programmer, Manager, and Analyst, corresponding to the rows in the dataframe.



In [24]:
#create a dictionary with the data 
data={'Name': ['Allu Arjun','Bavana','Divya unni','Gayathri','Mammuty','Mohanlal','Dileep','Kavya madavan','Jayaram','Dulqar'],
      'Age':[40,30,46,30,65,64,57,37,54,40],
       'Gender':['Male','Female','Female','Female','Male','Male','Male','Female','Male','Male']}

 #crete the data frame
df=pd.DataFrame(data)
#Add the occupation column
occupations= ['Actor','Actress','Actress','Actress','Actor','Actor','Actor','Actress','Actor','Actor']
df['occupations']=occupations
print(df)

            Name  Age  Gender occupations
0     Allu Arjun   40    Male       Actor
1         Bavana   30  Female     Actress
2     Divya unni   46  Female     Actress
3       Gayathri   30  Female     Actress
4        Mammuty   65    Male       Actor
5       Mohanlal   64    Male       Actor
6         Dileep   57    Male       Actor
7  Kavya madavan   37  Female     Actress
8        Jayaram   54    Male       Actor
9         Dulqar   40    Male       Actor


In [ ]:
----------------------------------------------------------------------------------------

##Exercise 6: (Score : 1)
Select the rows of the dataframe where the age is greater than or equal to 30.



In [32]:
#create a dictionary with the data 
data={'Name': ['Allu Arjun','Bavana','Divya unni','Gayathri','Mammuty','Mohanlal','Dileep','Kavya madavan','Jayaram','Dulqar'],
      'Age':[40,30,46,30,65,64,57,37,54,40],
       'Gender':['Male','Female','Female','Female','Male','Male','Male','Female','Male','Male'],
       'Occupations': ['Actor','Actress','Actress','Actress','Actor','Actor','Actor','Actress','Actor','Actor']}
df=pd.DataFrame(data)

#select  rows where age is  greater then or equal to 30
filtered_df=df[df['Age'] >=30]
print(filtered_df)

            Name  Age  Gender Occupations
0     Allu Arjun   40    Male       Actor
1         Bavana   30  Female     Actress
2     Divya unni   46  Female     Actress
3       Gayathri   30  Female     Actress
4        Mammuty   65    Male       Actor
5       Mohanlal   64    Male       Actor
6         Dileep   57    Male       Actor
7  Kavya madavan   37  Female     Actress
8        Jayaram   54    Male       Actor
9         Dulqar   40    Male       Actor


In [ ]:
---------------------------------------------------------------------------------------------------------


##Exercise 7: (Score : 2)
Convert this dataframe to a csv file and read that csv file, finally display the contents.



In [35]:
data={'Name': ['Allu Arjun','Bavana','Divya unni','Gayathri','Mammuty','Mohanlal','Dileep','Kavya madavan','Jayaram','Dulqar'],
      'Age':[40,30,46,30,65,64,57,37,54,40],
       'Gender':['Male','Female','Female','Female','Male','Male','Male','Female','Male','Male'],
       'Occupations': ['Actor','Actress','Actress','Actress','Actor','Actor','Actor','Actress','Actor','Actor']}
df=pd.DataFrame(data)
# Convert the DataFrame to a CSV file
df.to_csv('data.csv', index=False)

# Read the CSV file back into a DataFrame
df_from_csv = pd.read_csv('data.csv')

# Display the contents of the new DataFrame
print(df_from_csv)

            Name  Age  Gender Occupations
0     Allu Arjun   40    Male       Actor
1         Bavana   30  Female     Actress
2     Divya unni   46  Female     Actress
3       Gayathri   30  Female     Actress
4        Mammuty   65    Male       Actor
5       Mohanlal   64    Male       Actor
6         Dileep   57    Male       Actor
7  Kavya madavan   37  Female     Actress
8        Jayaram   54    Male       Actor
9         Dulqar   40    Male       Actor


In [ ]:
----------------------------------        -----------------------         ----------------------------------------